/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HeatTreatment } from "./HeatTreatment";
import { HeatTreatmentCountArgs } from "./HeatTreatmentCountArgs";
import { HeatTreatmentFindManyArgs } from "./HeatTreatmentFindManyArgs";
import { HeatTreatmentFindUniqueArgs } from "./HeatTreatmentFindUniqueArgs";
import { DeleteHeatTreatmentArgs } from "./DeleteHeatTreatmentArgs";
import { HeatTreatmentService } from "../heatTreatment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => HeatTreatment)
export class HeatTreatmentResolverBase {
  constructor(
    protected readonly service: HeatTreatmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "HeatTreatment",
    action: "read",
    possession: "any",
  })
  async _heatTreatmentsMeta(
    @graphql.Args() args: HeatTreatmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [HeatTreatment])
  @nestAccessControl.UseRoles({
    resource: "HeatTreatment",
    action: "read",
    possession: "any",
  })
  async heatTreatments(
    @graphql.Args() args: HeatTreatmentFindManyArgs
  ): Promise<HeatTreatment[]> {
    return this.service.heatTreatments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => HeatTreatment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "HeatTreatment",
    action: "read",
    possession: "own",
  })
  async heatTreatment(
    @graphql.Args() args: HeatTreatmentFindUniqueArgs
  ): Promise<HeatTreatment | null> {
    const result = await this.service.heatTreatment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => HeatTreatment)
  @nestAccessControl.UseRoles({
    resource: "HeatTreatment",
    action: "delete",
    possession: "any",
  })
  async deleteHeatTreatment(
    @graphql.Args() args: DeleteHeatTreatmentArgs
  ): Promise<HeatTreatment | null> {
    try {
      return await this.service.deleteHeatTreatment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
