/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FileUpload } from "./FileUpload";
import { FileUploadCountArgs } from "./FileUploadCountArgs";
import { FileUploadFindManyArgs } from "./FileUploadFindManyArgs";
import { FileUploadFindUniqueArgs } from "./FileUploadFindUniqueArgs";
import { DeleteFileUploadArgs } from "./DeleteFileUploadArgs";
import { FileUploadService } from "../fileUpload.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => FileUpload)
export class FileUploadResolverBase {
  constructor(
    protected readonly service: FileUploadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FileUpload",
    action: "read",
    possession: "any",
  })
  async _fileUploadsMeta(
    @graphql.Args() args: FileUploadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [FileUpload])
  @nestAccessControl.UseRoles({
    resource: "FileUpload",
    action: "read",
    possession: "any",
  })
  async fileUploads(
    @graphql.Args() args: FileUploadFindManyArgs
  ): Promise<FileUpload[]> {
    return this.service.fileUploads(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => FileUpload, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FileUpload",
    action: "read",
    possession: "own",
  })
  async fileUpload(
    @graphql.Args() args: FileUploadFindUniqueArgs
  ): Promise<FileUpload | null> {
    const result = await this.service.fileUpload(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FileUpload)
  @nestAccessControl.UseRoles({
    resource: "FileUpload",
    action: "delete",
    possession: "any",
  })
  async deleteFileUpload(
    @graphql.Args() args: DeleteFileUploadArgs
  ): Promise<FileUpload | null> {
    try {
      return await this.service.deleteFileUpload(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
